## Predicting Life Satisfaction
### Exploratory Data Analysis  
  
#### Objectives:  
* [Analysis of missing observations](#Analysis-of-Missing-Observations)
* [Analysis of categorical/numeric features](#Categorical-and-Numeric-Variables)
* [Correlation analysis](#Correlation-Analysis)
* [1 way/ 2 way variable plots (histograms, scatterplots, etc.)](#Visualizations)

### From Kaggle:
  
#### File descriptions  
* train.csv - the training set with some preprocesssing of values.  
* train_raw.csv - the training set with original responses (no preprocessing).  
  
#### Data fields
* v1-v270 - survey response fields
* cntry - survey respondent country
* satisfied - whether (1) or not (0) the survey respondent is 'very satisfied' with their life (training set only)

### Data Cleaning Steps
1) Categorize any missing response from (NA, "", ., .a, .b, .c, .d) to -1

2) Remove variables/columns that have more than 30% of responses missing

3) Remove observation/rows that have more than 30 resposnes missing to the remaining questions/variables

4) Encode country and language resposnes 

5) Clean data types of variables/columns to corresponding str/float/int64



In [1]:
# Import packages
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

# Set options
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999
pd.options.display.max_colwidth = -1

In [65]:
# Import data
train_raw = pd.read_csv("../01-data/train_raw.csv", low_memory = False)
train = pd.read_csv("../01-data/train.csv", low_memory = False)

# Fill missing responses with "." so that they can be counted and categorized as missing later on
train_no_blanks = train.fillna('.')
train_raw_no_blanks = train_raw.fillna('.')

# Custom data
codebook = pd.read_csv("../01-data/codebook_compact.csv", low_memory = False) # OG codebook+dtypes from codebook_long
codebook_labels = ['Variable', "Label"]

There are 30,080 observations with 273 columns (id, v1-v270, cntry, & satisfied) for each observartion.

In [3]:
# Mainly analyzing the preprocessed data
display(train_no_blanks.head())
train_no_blanks.shape

id  v1 v2  v3     v4     v5 v6 v7 v8 v9 v10 v11 v12 v13 v14  v15  v16  \
0  9948   2   2  74  11010  .a     2  2  2  2  1   1   2   2   1   0    0     
1  25601  4   2  58  11010  .a     2  2  2  2  1   2   2   2   2   0    0     
2  8592   6   2  47  11010  11010  2  2  1  2  1   .a  1   1   2   0    0     
3  29593  10  2  22  11010  .a     2  2  2  2  1   2   2   2   2   0    0     
4  4252   0   1  24  11010  .a     2  2  2  2  1   2   2   1   1   0    0     

  v17 v18 v19   v20 v21 v22 v23 v24 v25  v26  v27  v28  v29  v30  v31  v32  \
0  66  2   2   AT33  2   2   .a  1   66  0    0    0    0    1    0    0     
1  66  2   2   AT31  2   2   .a  1   66  0    0    0    0    1    0    0     
2  66  2   3   AT33  2   .a  .a  1   66  0    0    0    0    0    0    0     
3  66  2   10  AT12  2   .a  .a  1   66  0    0    0    0    1    0    0     
4  66  1   2   AT12  2   .a  .a  1   66  0    0    0    0    1    0    0     

   v33  v34 v35  v36  v37  v38  v39  v40  v41  v42 v43  v44  v45  v46  v47  \
0  0    0    3   0    0    0    0    0    0    0    2   0    0    1    0     
1  0    0    4   0    0    0    0    0    0    0    2   0    0    1    0     
2  0    0    4   0    0    0    0    0    0    0    2   0    0    1    0     
3  0    0    2   0    0    0    0    0    0    0    2   0    0    1    0     
4  0    0    3   0    0    0    0    0    0    0    2   0    0    1    0     

   v48  v49  v50  v51  v52 v53  v54  v55 v56  v57 v58  v59 v60  v61 v62  v63  \
0  0    0    0    0    0    2   0    0    3   322  3   322  3   322  .a  .a    
1  0    0    0    0    0    .a  0    0    3   322  2   212  2   212  .a  .a    
2  0    0    0    0    0    2   0    0    2   212  2   212  2   212  3   322   
3  0    0    0    0    0    2   0    0    3   322  3   322  3   322  .a  .a    
4  0    0    0    0    0    2   0    0    4   423  3   322  3   322  .a  .a    

  v64 v65 v66 v67 v68 v69 v70 v71 v72 v73 v74 v75 v76 v77 v78 v79 v80 v81 v82  \
0  10  3   3   3   .a  .a  1   .a  1   1   2   2   9   1   66  2   1   3   4    
1  12  3   2   2   .a  .a  1   .a  1   1   2   2   5   1   66  2   1   1   1    
2  9   2   2   2   3   .a  1   1   1   1   4   1   2   1   66  1   1   1   1    
3  6   3   3   3   .a  .a  1   .a  1   1   3   2   0   1   66  1   2   2   1    
4  13  5   3   3   .a  .a  1   .a  1   3   4   2   8   1   66  1   1   1   1    

  v83 v84 v85 v86 v87 v88 v89 v90 v91 v92 v93 v94 v95 v96 v97 v98 v99 v100  \
0  3   3   2   .   .   .   .   .a  .a  .a  .a  .a  .a  .a  .   5   2   1     
1  5   3   1   .   .   .   .   .a  .a  .a  .a  .a  .a  .a  .   4   3   1     
2  1   3   2   .   .   .   .   1   2   2   .a  .a  .a  .a  .   10  2   4     
3  1   1   1   .   .   .   .   .a  .a  .a  .a  .a  .a  .a  .   8   1   1     
4  1   1   1   .   .   .   .   .a  .a  .a  .a  .a  .a  .a  .   8   1   1     

  v101 v102 v103 v104 v105  v106  v107 v108 v109 v110 v111 v112 v113 v114  \
0  2    3    4    2    2    0     0     1    0    3    3    3    3    2     
1  2    4    5    2    3    0     0     1    6    3    2    4    3    3     
2  2    1    1    1    3    0     0     1    5    2    3    5    2    2     
3  2    1    1    2    3    1     0     1    0    4    4    2    2    2     
4  1    1    1    3    3    0     0     1    7    2    2    6    1    2     

  v115 v116 v117 v118 v119 v120 v121 v122 v123 v124 v125 v126 v127 v128  v129  \
0  3    6    3    2    2    2    0    0    .    1    1    12   2    4    4      
1  4    4    4    4    1    5    4    2    .    17   17   19   15   1    1      
2  3    5    2    2    2    5    3    6    .    18   18   17   28   3    3      
3  1    3    1    1    4    0    0    3    .    7    7    8    46   4    4      
4  3    4    1    6    2    7    8    3    .    29   29   19   20   3    3      

  v130 v131 v132  v133  v134 v135 v136 v137 v138 v139 v140 v141 v142 v143  \
0  9    25   107  2015  2015  4    5    3    4    1    5    3    3    2     
1  17   46   75   2015  2015  3    4    3    3    1 

(30080, 273)

### Analysis of Missing Observations
<a id="Analysis-of-Missing-Observations"></a>

Counting the frequency of unique responses/answers for each variable/question

In [4]:
frequency_train_data = pd.DataFrame()

for i in list(train_no_blanks)[1:]:
    grouped_data = train_no_blanks.groupby(i)["id"].count()
    num_unique_answers = grouped_data.size
    temp_dict = {"Question": [i] * num_unique_answers,
                 "Response": list(grouped_data.index),
                 "Frequency": list(grouped_data)}
    frequency_train_data = frequency_train_data.append(pd.DataFrame(temp_dict))

frequency_train_data.reset_index(inplace=True, drop=True)
temp = frequency_train_data.groupby(["Question","Response"]).agg({"Frequency":"sum"})
temp = temp.groupby(level=0).apply(lambda x: 100*x/float(x.sum()))
temp.reset_index(inplace=True)
temp = temp.rename(columns = {"Frequency":"Relative Frequency (%)"})
frequency_train_data = frequency_train_data.merge(temp, left_on = ["Question","Response"], right_on = ["Question","Response"], how = "left")
frequency_train_data = frequency_train_data.merge(codebook[["Variable","Label","Unique","Type_codebook_long"]], left_on = "Question", right_on = "Variable", how = "left").drop("Variable", axis=1)
frequency_train_data

Question Response  Frequency  Relative Frequency (%)  \
0     v1         .a       18         0.059840                 
1     v1         .b       546        1.815160                 
2     v1         .c       10         0.033245                 
3     v1         0        6405       21.293218                
4     v1         1        2432       8.085106                 
...   ..        ..         ...            ...                 
6408  cntry      PT       992        3.297872                 
6409  cntry      SE       1434       4.767287                 
6410  cntry      SI       950        3.158245                 
6411  satisfied  0        14454      48.051862                
6412  satisfied  1        15626      51.948138                

                                  Label  Unique Type_codebook_long  
0     Able to take active role in po...  11      double             
1     Able to take active role in po...  11      double             
2     Able to take active role in po...  11      double             
3     Able to take active role in po...  11      double             
4     Able to take active role in po...  11      double             
...                                 ...  ..         ...             
6408  Country                            21      string             
6409  Country                            21      string             
6410  Country                            21      string             
6411  Target                             2       float              
6412  Target                             2       float              

[6413 rows x 7 columns]

In [5]:
frequency_train_raw_data = pd.DataFrame()

for i in list(train_raw_no_blanks)[1:]:
    grouped_data = train_raw_no_blanks.groupby(i)["id"].count()
    num_unique_answers = grouped_data.size
    temp_dict = {"Question": [i] * num_unique_answers,
                 "Response": list(grouped_data.index),
                 "Frequency": list(grouped_data)}
    frequency_train_raw_data = frequency_train_raw_data.append(pd.DataFrame(temp_dict))

frequency_train_raw_data.reset_index(inplace=True, drop=True)
temp = frequency_train_raw_data.groupby(["Question","Response"]).agg({"Frequency":"sum"})
temp = temp.groupby(level=0).apply(lambda x: 100*x/float(x.sum()))
temp.reset_index(inplace=True)
temp = temp.rename(columns = {"Frequency":"Relative Frequency (%)"})
frequency_train_raw_data = frequency_train_raw_data.merge(temp, left_on = ["Question","Response"], right_on = ["Question","Response"], how = "left")
frequency_train_raw_data = frequency_train_raw_data.merge(codebook[["Variable","Label","Unique","Type_codebook_long"]], left_on = "Question", right_on = "Variable", how = "left").drop("Variable", axis=1)
frequency_train_raw_data

Question Response  Frequency  Relative Frequency (%)  \
0     v1         1        2432       8.085106                 
1     v1         2        3251       10.807846                
2     v1         3        3335       11.087101                
3     v1         4        2502       8.317819                 
4     v1         5        3349       11.133644                
...   ..        ..         ...             ...                
6402  cntry      PT       992        3.297872                 
6403  cntry      SE       1434       4.767287                 
6404  cntry      SI       950        3.158245                 
6405  satisfied  0        14454      48.051862                
6406  satisfied  1        15626      51.948138                

                                  Label  Unique Type_codebook_long  
0     Able to take active role in po...  11      double             
1     Able to take active role in po...  11      double             
2     Able to take active role in po...  11      double             
3     Able to take active role in po...  11      double             
4     Able to take active role in po...  11      double             
...                                 ...  ..         ...             
6402  Country                            21      string             
6403  Country                            21      string             
6404  Country                            21      string             
6405  Target                             2       float              
6406  Target                             2       float              

[6407 rows x 7 columns]

In [6]:
# If response contains a "." (., .a, .b, etc) then categorize as missing a response
frequency_train_data['Response Missing'] = pd.np.where(frequency_train_data.Response.str.find(".") > -1, 1, 0)
frequency_train_data

Question Response  Frequency  Relative Frequency (%)  \
0     v1         .a       18         0.059840                 
1     v1         .b       546        1.815160                 
2     v1         .c       10         0.033245                 
3     v1         0        6405       21.293218                
4     v1         1        2432       8.085106                 
...   ..        ..         ...            ...                 
6408  cntry      PT       992        3.297872                 
6409  cntry      SE       1434       4.767287                 
6410  cntry      SI       950        3.158245                 
6411  satisfied  0        14454      48.051862                
6412  satisfied  1        15626      51.948138                

                                  Label  Unique Type_codebook_long  \
0     Able to take active role in po...  11      double              
1     Able to take active role in po...  11      double              
2     Able to take active role in po...  11      double              
3     Able to take active role in po...  11      double              
4     Able to take active role in po...  11      double              
...                                 ...  ..         ...              
6408  Country                            21      string              
6409  Country                            21      string              
6410  Country                            21      string              
6411  Target                             2       float               
6412  Target                             2       float               

      Response Missing  
0     1                 
1     1                 
2     1                 
3     0                 
4     0                 
...  ..                 
6408  0                 
6409  0                 
6410  0                 
6411  0                 
6412  0                 

[6413 rows x 8 columns]

Calculate the percentage of resposnes missing for each question

In [7]:
missing_value_df = frequency_train_data.groupby(["Question","Response","Response Missing"]).agg({"Frequency":"sum"})
missing_value_df = missing_value_df.groupby(level=0).apply(lambda x: 100*x/float(x.sum()))
missing_value_df = missing_value_df.groupby(["Question","Response Missing"]).agg({"Frequency":"sum"})
missing_value_df = missing_value_df[missing_value_df.index.get_level_values("Response Missing")==1]
missing_value_df = missing_value_df[missing_value_df.index.get_level_values("Question")!="satisfied"]
missing_value_df.reset_index(inplace=True)
missing_value_df = missing_value_df.rename(columns = {"Frequency":"Percentage Missing"}).drop("Response Missing", axis=1)
missing_value_df = missing_value_df.merge(codebook[['Variable','Label','Unique','Type_codebook_long']], left_on = 'Question', right_on = 'Variable', how = 'left').drop("Variable", axis=1)
missing_value_df

37     2.905585            Important to behave properly       6        
39   v138     2.792553            Important to think new ideas a...  6        
40   v139     2.749335            Important that people are trea...  6        
41   v14      2.091090            Feel closer to a particular pa...  2        
42   v140     3.188165            Important to do what is told a...  6        
43   v141     2.772606            Important to have a good time      6        
44   v142     2.676197            Important to help people and c...  6        
45   v143     2.709441            Important to be loyal to frien...  6        
46   v144     2.882314            Important to be humble and mod...  6        
47   v145     3.125000            Important to get respect from ...  6        
48   v146     2.862367            Important to show abilities an...  6        
49   v147     3.341090            Important that government is s...  6        
50   v148     3.018617            Important to be successful and...  6        
51   v149     2.849069            Important to understand differ...  6        
52   v150     9.032580            Occupation, ISCO08                 549      
53   v151     64.361702           Occupation partner, ISCO08         524      
54   v152     8.071809            Responsible for supervising ot...  2        
55   v153     88.889628           What year you first came to li...  88       
56   v156     11.030585           Placement on left right scale      11       
57   v157     13.038564           Ever lived with a partner, wit...  2        
58   v158     86.439495           Main activity last 7 days          9        
59   v159     0.864362            Legal marital status, post coded   6        
60   v160     49.315160           Legal marital status               6        
61   v162     0.897606            Member of trade union or simil...  3        
62   v163     0.349069            Main activity, last 7 days. Al...  9        
63   v164     94.075798           Partner's main activity last 7...  8        
64   v165     0.242686            Mother born in country             2        
65   v166     0.485372            Administration of supplementar...  2        
66   v167     9.597739            Industry, NACE rev.2               88       
67   v168     73.397606           Number of people responsible f...  155      
68   v169     14.847074           Father's occupation when respo...  9        
69   v170     42.054521           Mother's occupation when respo...  9        
70   v171     0.372340            Lives with husband/wife/partne...  2        
71   v172     0.199468            Taken part in lawful public de...  2        
72   v173     54.498005           Ever had a paid job                2        
73   v174     64.295213           Year last in paid job              77       
74   v177     0.299202            How interested in politics         4        
75   v178     0.731383            Most people try to take advant...  11       
76   v179     0.372340            Most of the time people helpfu...  11       
77   v18      0.216090            Contacted politician or govern...  2        
78   v180     0.196144            Most people can be trusted or ...  11       
79   v181     1.386303            How often pray apart from at r...  7        
80   v182     52.995346           How close to party                 4        
81   v183     2.310505            Political system allows people...  11       
82   v184     2.430186            Political system allows people...  11       
83   v186     0.425532            How often attend religious ser...  7        
84   v187     0.482048            Belonging to particular religi...  2        
85   v188     58.474069           Ever belonging to particular r...  2        
86   v189     0.791223            How religious are you              11       
87   v19      1.788564            Confident in own ability to pa...  11       
88   v190     42.134309           Religion or denominatio

Let's look at what variables/questions have the highest missing reponses %

In [8]:
percent = 30
cols_missing = missing_value_df[missing_value_df["Percentage Missing"] > percent]
n_cols_missing = len(missing_value_df[missing_value_df["Percentage Missing"] > percent])
print("There are " + str(n_cols_missing) + " features with over " + str(percent) + "% missing.")
display(cols_missing)

There are 71 features with over 30% missing.


Question  Percentage Missing                              Label  Unique  \
10   v11      35.954122           Ever had children living in ho...  2        
25   v123     92.061170           Place of interview: East, West...  2        
53   v151     64.361702           Occupation partner, ISCO08         524      
55   v153     88.889628           What year you first came to li...  88       
58   v158     86.439495           Main activity last 7 days          9        
60   v160     49.315160           Legal marital status               6        
63   v164     94.075798           Partner's main activity last 7...  8        
67   v168     73.397606           Number of people responsible f...  155      
69   v170     42.054521           Mother's occupation when respo...  9        
72   v173     54.498005           Ever had a paid job                2        
73   v174     64.295213           Year last in paid job              77       
80   v182     52.995346           How close to party                 4        
85   v188     58.474069           Ever belonging to particular r...  2        
88   v190     42.134309           Religion or denomination belon...  8        
89   v191     89.697473           Religion or denomination belon...  8        
90   v192     99.883644           Tenth person in household: rel...  3        
91   v193     99.930186           Eleventh person in household: ...  3        
92   v194     99.980053           Twelfth person in household: r...  2        
93   v195     99.996676           Thirteenth person in household...  1        
95   v197     56.392952           Third person in household: rel...  5        
96   v198     74.378324           Fourth person in household: re...  5        
97   v199     90.601729           Fifth person in household: rel...  5        
99   v200     96.672207           Sixth person in household: rel...  5        
100  v201     98.843085           Seventh person in household: r...  5        
101  v202     99.574468           Eighth person in household: re...  3        
102  v203     99.813830           Ninth person in household: rel...  3        
103  v204     99.883644           Tenth person in household: rel...  4        
104  v205     99.930186           Eleventh person in household: ...  4        
105  v206     99.980053           Twelfth person in household: r...  2        
106  v207     99.996676           Thirteenth person in household...  1        
108  v209     56.392952           Third person in household: rel...  6        
110  v210     74.378324           Fourth person in household: re...  6        
111  v211     90.601729           Fifth person in household: rel...  6        
112  v212     96.672207           Sixth person in household: rel...  6        
113  v213     98.843085           Seventh person in household: r...  6        
114  v214     99.574468           Eighth person in household: re...  4        
115  v215     99.813830           Ninth person in household: rel...  4        
116  v216     41.296543           Relationship with husband/wife...  6        
118  v22      52.446809           Control paid work last 7 days      2        
129  v23      77.140957           Partner, control paid work las...  2        
142  v241     71.768617           Any period of unemployment and...  2        
144  v243     71.745346           Any period of unemployment and...  2        
149  v252     65.315824           Hours normally worked a week i...  91       
156  v259     99.893617           Year of birth of tenth person ...  15       
157  v260     99.940160           Year of birth of eleventh pers...  11       
158  v261     99.983378           Year of birth of twelfth perso...  8        
159  v262     99.996676           Year of birth of thirteenth pe...  1        
161  v264     56.978059           Year of birth of third person ...  99       
162  v265     74.644282           Year of birth of fourth person...  92       
163  v266     90.764628           Year of birth of fif

Let's drop these columns

In [9]:
drop_missing = cols_missing.Question.to_list()
train_v2 = train_no_blanks.drop(columns = drop_missing)
train_v2

id  v1 v2  v3     v4 v6 v7 v8 v9 v10 v12 v13 v14  v15  v16 v17 v18  \
0      9948   2   2  74  11010  2  2  2  2  1   2   2   1   0    0    66  2    
1      25601  4   2  58  11010  2  2  2  2  1   2   2   2   0    0    66  2    
2      8592   6   2  47  11010  2  2  1  2  1   1   1   2   0    0    66  2    
3      29593  10  2  22  11010  2  2  2  2  1   2   2   2   0    0    66  2    
4      4252   0   1  24  11010  2  2  2  2  1   2   1   1   0    0    66  1    
...     ...  ..  ..  ..    ... .. .. .. .. ..  ..  ..  ..  ..   ..    .. ..    
30075  34440  0   1  72  14120  2  2  2  2  1   2   1   2   0    0    66  2    
30076  13566  0   1  38  14120  2  2  2  2  1   2   1   2   0    0    66  2    
30077  29824  5   2  49  14120  2  2  2  2  1   1   1   2   0    0    66  2    
30078  9573   0   1  16  14120  2  2  2  2  1   2   1   2   0    0    66  2    
30079  13518  4   2  66  14120  2  2  2  2  1   2   2   1   0    0    66  2    

      v19    v20 v21 v24 v25  v26  v27  v28  v29  v30  v31  v32  v33  v34 v35  \
0      2   AT33   2   1   66  0    0    0    0    1    0    0    0    0    3    
1      2   AT31   2   1   66  0    0    0    0    1    0    0    0    0    4    
2      3   AT33   2   1   66  0    0    0    0    0    0    0    0    0    4    
3      10  AT12   2   1   66  0    0    0    0    1    0    0    0    0    2    
4      2   AT12   2   1   66  0    0    0    0    1    0    0    0    0    3    
...   ..    ...  ..  ..   .. ..   ..   ..   ..   ..   ..   ..   ..   ..   ..    
30075  4   SI017  2   1   66  0    0    0    0    0    0    0    0    0    4    
30076  0   SI021  2   1   66  0    0    0    0    1    0    0    0    0    4    
30077  5   SI011  2   1   66  0    0    0    0    0    0    0    0    0    5    
30078  0   SI018  2   1   66  0    0    0    0    1    0    0    0    0    3    
30079  3   SI012  2   1   66  0    0    0    0    0    0    0    0    0    4    

       v36  v37  v38  v39  v40  v41  v42 v43  v44  v45  v46  v47  v48  v49  \
0      0    0    0    0    0    0    0    2   0    0    1    0    0    0     
1      0    0    0    0    0    0    0    2   0    0    1    0    0    0     
2      0    0    0    0    0    0    0    2   0    0    1    0    0    0     
3      0    0    0    0    0    0    0    2   0    0    1    0    0    0     
4      0    0    0    0    0    0    0    2   0    0    1    0    0    0     
...   ..   ..   ..   ..   ..   ..   ..   ..  ..   ..   ..   ..   ..   ..     
30075  0    0    0    0    0    0    0    2   0    0    1    0    0    0     
30076  0    0    0    0    0    0    0    2   0    0    1    0    0    0     
30077  0    0    0    0    0    0    0    2   0    0    1    0    0    0     
30078  0    0    0    0    0    0    0    2   0    0    1    0    0    0     
30079  0    0    0    0    0    0    0    2   0    0    1    0    0    0     

       v50  v51  v52 v53  v54  v55 v56  v57 v58  v59 v60  v61 v64 v65 v66 v67  \
0      0    0    0    2   0    0    3   322  3   322  3   322  10  3   3   3    
1      0    0    0    .a  0    0    3   322  2   212  2   212  12  3   2   2    
2      0    0    0    2   0    0    2   212  2   212  2   212  9   2   2   2    
3      0    0    0    2   0    0    3   322  3   322  3   322  6   3   3   3    
4      0    0    0    2   0    0    4   423  3   322  3   322  13  5   3   3    
...   ..   ..   ..   ..  ..   ..   ..   ... ..   ... ..   ...  .. ..  ..  ..    
30075  0    0    0    2   0    0    3   321  2   213  2   213  11  3   2   2    
30076  0    0    0    2   0    0    3   323  3   321  3   321  11  4   3   3    
30077  0    0    0    2   0    0    2   213  2   213  2   213  8   2   2   2    
30078  0    0    0    2   1    0    2   213  3   313  3   323  10  2   4   4    
30079  0    0    0    2   0    0    3   323  2   213  2   213  12  4   2   2    

      v70 v72 v73 v74 v75 v76 v77 v78 v79 v80 v81 v82 v83 v84 v85 v90 v98 v99  \
0      1   1   1   2   2   9   1   66  2   1   3   4   3   3   2   .a  5   2    
1   

In [19]:
train_raw_v2 = train_raw_no_blanks.drop(columns = drop_missing)
train_raw_v2

48                v149  \
0      Like me            Not like me at all  Not like me          
1      Somewhat like me   Somewhat like me    Very much like me    
2      Like me            Not like me         A little like me     
3      Very much like me  Somewhat like me    Not like me at all   
4      Like me            Somewhat like me    Somewhat like me     
...        ...                         ...                 ...     
30075  Like me            Like me             Like me              
30076  Like me            Somewhat like me    Somewhat like me     
30077  Like me            Very much like me   Like me              
30078  Like me            Somewhat like me    Like me              
30079  Like me            Like me             Like me              

                                                                         v150  \
0      Office supervisors                                                       
1      Spray painters and varnishers                                            
2      Cleaners and helpers in offices, hotels and other establishments         
3      Motor vehicle mechanics and repairers                                    
4      Accounting and bookkeeping clerks                                        
...                                  ...                                        
30075  Business services and administration managers not elsewhere classified   
30076  Commercial sales representatives                                         
30077  Food and related products machine operators                              
30078  Not applicable                                                           
30079  Electrical mechanics and fitters                                         

                 v152 v154 v155   v156       v157  \
0      Yes             GER  0    3      No          
1      No              GER  0    5      Refusal     
2      Yes             GER  0    4      No answer   
3      No              GER  0    Right  Yes         
4      No              GER  0    4      No          
...    ..              ... ..   ..      ..          
30075  Yes             SLV  0    5      No          
30076  No              SLV  0    5      No          
30077  No              SLV  0    6      No          
30078  Not applicable  SLV  0    5      No          
30079  Yes             SLV  0    7      No          

                                                                     v159  \
0      Widowed/civil partner died                                           
1      None of these (NEVER married or in legally registered civil union)   
2      Legally married                                                      
3      Legally divorced/civil union dissolved                               
4      None of these (NEVER married or in legally registered civil union)   
...                                                                   ...   
30075  Legally married                                                      
30076  None of these (NEVER married or in legally registered civil union)   
30077  Legally married                                                      
30078  None of these (NEVER married or in legally registered civil union)   
30079  Legally married                                                      

      v161             v162                         v163 v165  \
0      66   Yes, previously  Retired                      Yes   
1      66   No               Unemployed, looking for job  Yes   
2      66   No               Paid work                    Yes   
3      66   No               Paid work                    Yes   
4      66   No               Paid work                    Yes   
...    ..   ..                     ...                    ...   
30075  66   Yes, previously  Retired                      Yes   
30076  66   No               Paid work                    Yes   
30077  66   Yes, currently   Paid work                    Yes   
30078  66   No               Education  

To deal with missing responses, we will group all missing responses (., .a, .b, etc) together and code them as -1

In [25]:
train_v2 = train_v2.replace([".", ".a", ".b", ".c", ".d"], [-1, -1, -1, -1, -1])
train_raw_v2 = train_raw_v2.replace([".", ".a", ".b", ".c", ".d"], [-1, -1, -1, -1, -1])

Not only are columns with lots of missing responses concerning, we should also check if there are observations/rows with many missing responses that can be removed as well. This is done after the columns were dropped previously.

In [12]:
train_v2["Num -1's per person"] = (train_v2[list(train_v2)[1:]] == -1).sum(axis=1)
tolerance = 30
rows_many_missing_entries = train_v2[train_v2["Num -1's per person"] > tolerance]
n_rows_missing = len(rows_many_missing_entries)
print("There are " + str(n_rows_missing) + " entries with over " + str(tolerance) + " missing responses to the survey.")
rows_missing_index = list(rows_many_missing_entries.index.values)
rows_missing_ids = list(train_v2.loc[rows_missing_index]["id"])

There are 499 entries with over 30 missing responses to the survey.


New data set to work with:

In [22]:
train_v3 = train_v2.drop(index = rows_missing_index).drop(columns = "Num -1's per person")
train_raw_v3 = train_raw_v2.drop(index = rows_missing_index)
display(train_v3)
display(train_raw_v3)

id  v1 v2  v3     v4 v6 v7 v8 v9 v10 v12 v13 v14  v15  v16 v17 v18  \
0      9948   2   2  74  11010  2  2  2  2  1   2   2   1   0    0    66  2    
1      25601  4   2  58  11010  2  2  2  2  1   2   2   2   0    0    66  2    
2      8592   6   2  47  11010  2  2  1  2  1   1   1   2   0    0    66  2    
3      29593  10  2  22  11010  2  2  2  2  1   2   2   2   0    0    66  2    
4      4252   0   1  24  11010  2  2  2  2  1   2   1   1   0    0    66  1    
...     ...  ..  ..  ..    ... .. .. .. .. ..  ..  ..  ..  ..   ..    .. ..    
30075  34440  0   1  72  14120  2  2  2  2  1   2   1   2   0    0    66  2    
30076  13566  0   1  38  14120  2  2  2  2  1   2   1   2   0    0    66  2    
30077  29824  5   2  49  14120  2  2  2  2  1   1   1   2   0    0    66  2    
30078  9573   0   1  16  14120  2  2  2  2  1   2   1   2   0    0    66  2    
30079  13518  4   2  66  14120  2  2  2  2  1   2   2   1   0    0    66  2    

      v19    v20 v21 v24 v25  v26  v27  v28  v29  v30  v31  v32  v33  v34 v35  \
0      2   AT33   2   1   66  0    0    0    0    1    0    0    0    0    3    
1      2   AT31   2   1   66  0    0    0    0    1    0    0    0    0    4    
2      3   AT33   2   1   66  0    0    0    0    0    0    0    0    0    4    
3      10  AT12   2   1   66  0    0    0    0    1    0    0    0    0    2    
4      2   AT12   2   1   66  0    0    0    0    1    0    0    0    0    3    
...   ..    ...  ..  ..   .. ..   ..   ..   ..   ..   ..   ..   ..   ..   ..    
30075  4   SI017  2   1   66  0    0    0    0    0    0    0    0    0    4    
30076  0   SI021  2   1   66  0    0    0    0    1    0    0    0    0    4    
30077  5   SI011  2   1   66  0    0    0    0    0    0    0    0    0    5    
30078  0   SI018  2   1   66  0    0    0    0    1    0    0    0    0    3    
30079  3   SI012  2   1   66  0    0    0    0    0    0    0    0    0    4    

       v36  v37  v38  v39  v40  v41  v42 v43  v44  v45  v46  v47  v48  v49  \
0      0    0    0    0    0    0    0    2   0    0    1    0    0    0     
1      0    0    0    0    0    0    0    2   0    0    1    0    0    0     
2      0    0    0    0    0    0    0    2   0    0    1    0    0    0     
3      0    0    0    0    0    0    0    2   0    0    1    0    0    0     
4      0    0    0    0    0    0    0    2   0    0    1    0    0    0     
...   ..   ..   ..   ..   ..   ..   ..   ..  ..   ..   ..   ..   ..   ..     
30075  0    0    0    0    0    0    0    2   0    0    1    0    0    0     
30076  0    0    0    0    0    0    0    2   0    0    1    0    0    0     
30077  0    0    0    0    0    0    0    2   0    0    1    0    0    0     
30078  0    0    0    0    0    0    0    2   0    0    1    0    0    0     
30079  0    0    0    0    0    0    0    2   0    0    1    0    0    0     

       v50  v51  v52 v53  v54  v55 v56  v57 v58  v59 v60  v61 v64 v65 v66 v67  \
0      0    0    0    2   0    0    3   322  3   322  3   322  10  3   3   3    
1      0    0    0    -1  0    0    3   322  2   212  2   212  12  3   2   2    
2      0    0    0    2   0    0    2   212  2   212  2   212  9   2   2   2    
3      0    0    0    2   0    0    3   322  3   322  3   322  6   3   3   3    
4      0    0    0    2   0    0    4   423  3   322  3   322  13  5   3   3    
...   ..   ..   ..   ..  ..   ..   ..   ... ..   ... ..   ...  .. ..  ..  ..    
30075  0    0    0    2   0    0    3   321  2   213  2   213  11  3   2   2    
30076  0    0    0    2   0    0    3   323  3   321  3   321  11  4   3   3    
30077  0    0    0    2   0    0    2   213  2   213  2   213  8   2   2   2    
30078  0    0    0    2   1    0    2   213  3   313  3   323  10  2   4   4    
30079  0    0    0    2   0    0    3   323  2   213  2   213  12  4   2   2    

      v70 v72 v73 v74 v75 v76 v77 v78 v79 v80 v81 v82 v83 v84 v85 v90 v98 v99  \
0      1   1   1   2   2   9   1   66  2   1   3   4   3   3   2   -1  5   2    
1   

id               v1         v2  v3            v4  v6  v7   v8  v9  \
0      9948   2                Safe       74  Austrian nfs  No  No  No   No   
1      25601  4                Safe       58  Austrian nfs  No  No  No   No   
2      8592   6                Safe       47  Austrian nfs  No  No  Yes  No   
3      29593  Completely able  Safe       22  Austrian nfs  No  No  No   No   
4      4252   Not at all able  Very safe  24  Austrian nfs  No  No  No   No   
...     ...               ...        ...  ..           ...  ..  ..  ..   ..   
30075  34440  Not at all able  Very safe  72  Slovene nfs   No  No  No   No   
30076  13566  Not at all able  Very safe  38  Slovene nfs   No  No  No   No   
30077  29824  5                Safe       49  Slovene nfs   No  No  No   No   
30078  9573   Not at all able  Very safe  16  Slovene nfs   No  No  No   No   
30079  13518  4                Safe       66  Slovene nfs   No  No  No   No   

       v10                                               v12  \
0      Yes  Does not                                           
1      Yes  Does not                                           
2      Yes  Respondent lives with children at household grid   
3      Yes  Does not                                           
4      Yes  Does not                                           
...    ...       ...                                           
30075  Yes  Does not                                           
30076  Yes  Does not                                           
30077  Yes  Respondent lives with children at household grid   
30078  Yes  Does not                                           
30079  Yes  Does not                                           

                                   v13  v14         v15         v16 v17  v18  \
0      Some of the time                 Yes  Not marked  Not marked  66  No    
1      Some of the time                 No   Not marked  Not marked  66  No    
2      None or almost none of the time  No   Not marked  Not marked  66  No    
3      Some of the time                 No   Not marked  Not marked  66  No    
4      None or almost none of the time  Yes  Not marked  Not marked  66  Yes   
...                                ...  ...         ...         ...  ..  ...   
30075  None or almost none of the time  No   Not marked  Not marked  66  No    
30076  None or almost none of the time  No   Not marked  Not marked  66  No    
30077  None or almost none of the time  No   Not marked  Not marked  66  No    
30078  None or almost none of the time  No   Not marked  Not marked  66  No    
30079  Some of the time                 Yes  Not marked  Not marked  66  No    

                        v19    v20 v21  v24 v25         v26         v27  \
0      2                     AT33   No  Yes  66  Not marked  Not marked   
1      2                     AT31   No  Yes  66  Not marked  Not marked   
2      3                     AT33   No  Yes  66  Not marked  Not marked   
3      Completely confident  AT12   No  Yes  66  Not marked  Not marked   
4      2                     AT12   No  Yes  66  Not marked  Not marked   
...   ..                      ...   ..  ...  ..         ...         ...   
30075  4                     SI017  No  Yes  66  Not marked  Not marked   
30076  Not at all confident  SI021  No  Yes  66  Not marked  Not marked   
30077  5                     SI011  No  Yes  66  Not marked  Not marked   
30078  Not at all confident  SI018  No  Yes  66  Not marked  Not marked   
30079  3                     SI012  No  Yes  66  Not marked  Not marked   

              v28         v29         v30         v31         v32         v33  \
0      Not marked  Not marked  Marked      Not marked  Not marked  Not marked   
1      Not marked  Not marked  Marked      Not marked  Not marked  Not marked   
2      Not marked  Not marked  Not marked  Not marked  Not marked  Not marked   
3      Not marked  Not marked  Marked      Not marked  Not marked  Not marked   
4      Not marked  Not ma

### Categorical and Numeric Variables
<a id="Categorical-and-Numeric-Variables"></a>

In [23]:
frequency_train_v3_data = pd.DataFrame()

for i in list(train_v3)[1:]:
    grouped_data = train_v3.groupby(i)['id'].count()
    num_unique_answers = grouped_data.size
    temp_dict = {'Question': [i]*num_unique_answers,
                 'Response': list(grouped_data.index),
                 'Frequency': list(grouped_data)}
    frequency_train_v3_data = frequency_train_v3_data.append(pd.DataFrame(temp_dict))
frequency_train_v3_data.reset_index(inplace=True, drop=True)
temp = frequency_train_v3_data.groupby(["Question","Response"]).agg({"Frequency":"sum"})
temp = temp.groupby(level=0).apply(lambda x: 100*x/float(x.sum()))
temp.reset_index(inplace=True)
temp = temp.rename(columns = {"Frequency":"Relative Frequency (%)"})
frequency_train_v3_data = frequency_train_v3_data.merge(temp, left_on = ['Question','Response'], right_on = ['Question','Response'], how = 'left')
frequency_train_v3_data = frequency_train_v3_data.merge(codebook[['Variable','Label','Unique','Type_codebook_long']], left_on = 'Question', right_on = 'Variable', how = 'left').drop("Variable", axis=1)
frequency_train_v3_data

Question Response  Frequency  Relative Frequency (%)  \
0     v1         -1       500        1.690274                 
1     v1         0        6204       20.972922                
2     v1         1        2393       8.089652                 
3     v1         10       899        3.039113                 
4     v1         2        3211       10.854941                
...   ..        ..         ...             ...                
4015  cntry      PT       978        3.306176                 
4016  cntry      SE       1419       4.796998                 
4017  cntry      SI       926        3.130388                 
4018  satisfied  0        14144      47.814476                
4019  satisfied  1        15437      52.185524                

                                  Label  Unique Type_codebook_long  
0     Able to take active role in po...  11      double             
1     Able to take active role in po...  11      double             
2     Able to take active role in po...  11      double             
3     Able to take active role in po...  11      double             
4     Able to take active role in po...  11      double             
...                                 ...  ..         ...             
4015  Country                            21      string             
4016  Country                            21      string             
4017  Country                            21      string             
4018  Target                             2       float              
4019  Target                             2       float              

[4020 rows x 7 columns]

In [27]:
frequency_train_raw_v3_data = pd.DataFrame()

for i in list(train_raw_v3)[1:]:
    grouped_data = train_raw_v3.groupby(i)['id'].count()
    num_unique_answers = grouped_data.size
    temp_dict = {'Question': [i]*num_unique_answers,
                 'Response': list(grouped_data.index),
                 'Frequency': list(grouped_data)}
    frequency_train_raw_v3_data = frequency_train_raw_v3_data.append(pd.DataFrame(temp_dict))
frequency_train_raw_v3_data.reset_index(inplace=True, drop=True)
temp = frequency_train_raw_v3_data.groupby(["Question","Response"]).agg({"Frequency":"sum"})
temp = temp.groupby(level=0).apply(lambda x: 100*x/float(x.sum()))
temp.reset_index(inplace=True)
temp = temp.rename(columns = {"Frequency":"Relative Frequency (%)"})
frequency_train_raw_v3_data = frequency_train_raw_v3_data.merge(temp, left_on = ['Question','Response'], right_on = ['Question','Response'], how = 'left')
frequency_train_raw_v3_data = frequency_train_raw_v3_data.merge(codebook[['Variable','Label','Unique','Type_codebook_long']], left_on = 'Question', right_on = 'Variable', how = 'left').drop("Variable", axis=1)
frequency_train_raw_v3_data

Question Response  Frequency  Relative Frequency (%)  \
0     v1         1        2393       8.089652                 
1     v1         2        3211       10.854941                
2     v1         3        3293       11.132146                
3     v1         4        2481       8.387140                 
4     v1         5        3310       11.189615                
...   ..        ..         ...             ...                
4324  cntry      PT       978        3.306176                 
4325  cntry      SE       1419       4.796998                 
4326  cntry      SI       926        3.130388                 
4327  satisfied  0        14144      47.814476                
4328  satisfied  1        15437      52.185524                

                                  Label  Unique Type_codebook_long  
0     Able to take active role in po...  11      double             
1     Able to take active role in po...  11      double             
2     Able to take active role in po...  11      double             
3     Able to take active role in po...  11      double             
4     Able to take active role in po...  11      double             
...                                 ...  ..         ...             
4324  Country                            21      string             
4325  Country                            21      string             
4326  Country                            21      string             
4327  Target                             2       float              
4328  Target                             2       float              

[4329 rows x 7 columns]

Most of the variables have already been encoded via the preprocessing. The variables identified to be strings, according to codebook_long are: v17, v20, v25, v78, v154, v155, v161, cntry - these are all country/region codes or language codes.

In [60]:
cat_cols = ["v17", "v20", "v25", "v78", "v154", "v155", "v161", "cntry"]
cat_df = train_v3[cat_cols]
# change variable type to str
train_v3[cat_cols] = train_v3[cat_cols].astype(str)

In [30]:
# concerning resposnes: 2, 3, 4, 6, 66, 77, 88, 99
frequency_train_v3_data[frequency_train_v3_data["Question"]=="v17"]

Question Response  Frequency  Relative Frequency (%)             Label  \
313  v17      2        25         0.084514                Country of birth   
314  v17      3        8          0.027044                Country of birth   
315  v17      4        7          0.023664                Country of birth   
316  v17      66       26275      88.823907               Country of birth   
317  v17      77       2          0.006761                Country of birth   
318  v17      88       1          0.003381                Country of birth   
319  v17      99       173        0.584835                Country of birth   
320  v17      AF       13         0.043947                Country of birth   
321  v17      AL       3          0.010142                Country of birth   
322  v17      AM       4          0.013522                Country of birth   
323  v17      AO       14         0.047328                Country of birth   
324  v17      AR       27         0.091275                Country of birth   
325  v17      AS       1          0.003381                Country of birth   
326  v17      AT       26         0.087894                Country of birth   
327  v17      AU       6          0.020283                Country of birth   
328  v17      AW       3          0.010142                Country of birth   
329  v17      AX       1          0.003381                Country of birth   
330  v17      AZ       10         0.033805                Country of birth   
331  v17      BA       74         0.250161                Country of birth   
332  v17      BD       5          0.016903                Country of birth   
333  v17      BE       19         0.064230                Country of birth   
334  v17      BF       2          0.006761                Country of birth   
335  v17      BG       21         0.070992                Country of birth   
336  v17      BI       1          0.003381                Country of birth   
337  v17      BJ       2          0.006761                Country of birth   
338  v17      BO       4          0.013522                Country of birth   
339  v17      BQ       1          0.003381                Country of birth   
340  v17      BR       36         0.121700                Country of birth   
341  v17      BY       58         0.196072                Country of birth   
342  v17      CA       7          0.023664                Country of birth   
343  v17      CD       6          0.020283                Country of birth   
344  v17      CF       1          0.003381                Country of birth   
345  v17      CG       3          0.010142                Country of birth   
346  v17      CH       5          0.016903                Country of birth   
347  v17      CI       5          0.016903                Country of birth   
348  v17      CL       11         0.037186                Country of birth   
349  v17      CM       2          0.006761                Country of birth   
350  v17      CN       24         0.081133                Country of birth   
351  v17      CO       17         0.057469                Country of birth   
352  v17      CR       1          0.003381                Country of birth   
353  v17      CU       7          0.023664                Country of birth   
354  v17      CV       8          0.027044                Country of birth   
355  v17      CW       6          0.020283                Country of birth   
356  v17      CY       1          0.003381                Country of birth   
357  v17      CZ       18         0.060850                Country of birth   
358  v17      DE       153        0.517224                Country of birth   
359  v17      DK       15         0.050708                Country of birth   
360  v17      DO       5          0.016903                Country of birth   
361  v17      DZ       50         0.169027                Country of birth   
362  v17      EC       10         0.033805                Country of birth   
363  v17      EE       19 

In [31]:
frequency_train_raw_v3_data[frequency_train_raw_v3_data["Question"]=="v17"]

Question Response  Frequency  Relative Frequency (%)             Label  \
332  v17      2        25         0.084514                Country of birth   
333  v17      3        8          0.027044                Country of birth   
334  v17      4        7          0.023664                Country of birth   
335  v17      66       26275      88.823907               Country of birth   
336  v17      77       2          0.006761                Country of birth   
337  v17      88       1          0.003381                Country of birth   
338  v17      99       173        0.584835                Country of birth   
339  v17      AF       13         0.043947                Country of birth   
340  v17      AL       3          0.010142                Country of birth   
341  v17      AM       4          0.013522                Country of birth   
342  v17      AO       14         0.047328                Country of birth   
343  v17      AR       27         0.091275                Country of birth   
344  v17      AS       1          0.003381                Country of birth   
345  v17      AT       26         0.087894                Country of birth   
346  v17      AU       6          0.020283                Country of birth   
347  v17      AW       3          0.010142                Country of birth   
348  v17      AX       1          0.003381                Country of birth   
349  v17      AZ       10         0.033805                Country of birth   
350  v17      BA       74         0.250161                Country of birth   
351  v17      BD       5          0.016903                Country of birth   
352  v17      BE       19         0.064230                Country of birth   
353  v17      BF       2          0.006761                Country of birth   
354  v17      BG       21         0.070992                Country of birth   
355  v17      BI       1          0.003381                Country of birth   
356  v17      BJ       2          0.006761                Country of birth   
357  v17      BO       4          0.013522                Country of birth   
358  v17      BQ       1          0.003381                Country of birth   
359  v17      BR       36         0.121700                Country of birth   
360  v17      BY       58         0.196072                Country of birth   
361  v17      CA       7          0.023664                Country of birth   
362  v17      CD       6          0.020283                Country of birth   
363  v17      CF       1          0.003381                Country of birth   
364  v17      CG       3          0.010142                Country of birth   
365  v17      CH       5          0.016903                Country of birth   
366  v17      CI       5          0.016903                Country of birth   
367  v17      CL       11         0.037186                Country of birth   
368  v17      CM       2          0.006761                Country of birth   
369  v17      CN       24         0.081133                Country of birth   
370  v17      CO       17         0.057469                Country of birth   
371  v17      CR       1          0.003381                Country of birth   
372  v17      CU       7          0.023664                Country of birth   
373  v17      CV       8          0.027044                Country of birth   
374  v17      CW       6          0.020283                Country of birth   
375  v17      CY       1          0.003381                Country of birth   
376  v17      CZ       18         0.060850                Country of birth   
377  v17      DE       153        0.517224                Country of birth   
378  v17      DK       15         0.050708                Country of birth   
379  v17      DO       5          0.016903                Country of birth   
380  v17      DZ       50         0.169027                Country of birth   
381  v17      EC       10         0.033805                Country of birth   
382  v17      EE       19 

For v17, 89% of responses are '66' for 'Country of birth' in both the raw and preprocessed data. Will just leave this column in there since its not a preprocessing error - maybe drop this column if there is another variable that is highly correlated with this

In [32]:
# concerning responses: 99999
frequency_train_v3_data[frequency_train_v3_data["Question"]=="v20"]

0      ES12     40         0.135222                Region  251      
558  v20      ES13     20         0.067611                Region  251      
559  v20      ES21     72         0.243399                Region  251      
560  v20      ES22     23         0.077753                Region  251      
561  v20      ES23     16         0.054089                Region  251      
562  v20      ES24     49         0.165647                Region  251      
563  v20      ES30     200        0.676110                Region  251      
564  v20      ES41     85         0.287347                Region  251      
565  v20      ES42     77         0.260302                Region  251      
566  v20      ES43     40         0.135222                Region  251      
567  v20      ES51     201        0.679490                Region  251      
568  v20      ES52     156        0.527366                Region  251      
569  v20      ES53     26         0.087894                Region  251      
570  v20      ES61     287        0.970217                Region  251      
571  v20      ES62     41         0.138602                Region  251      
572  v20      ES63     4          0.013522                Region  251      
573  v20      ES64     4          0.013522                Region  251      
574  v20      ES70     62         0.209594                Region  251      
575  v20      FI193    73         0.246780                Region  251      
576  v20      FI194    74         0.250161                Region  251      
577  v20      FI195    55         0.185930                Region  251      
578  v20      FI196    90         0.304249                Region  251      
579  v20      FI197    149        0.503702                Region  251      
580  v20      FI1B1    423        1.429972                Region  251      
581  v20      FI1C1    137        0.463135                Region  251      
582  v20      FI1C2    52         0.175789                Region  251      
583  v20      FI1C3    58         0.196072                Region  251      
584  v20      FI1C4    67         0.226497                Region  251      
585  v20      FI1C5    35         0.118319                Region  251      
586  v20      FI1D1    38         0.128461                Region  251      
587  v20      FI1D2    88         0.297488                Region  251      
588  v20      FI1D3    50         0.169027                Region  251      
589  v20      FI1D4    33         0.111558                Region  251      
590  v20      FI1D5    23         0.077753                Region  251      
591  v20      FI1D6    123        0.415807                Region  251      
592  v20      FI1D7    61         0.206213                Region  251      
593  v20      FI200    10         0.033805                Region  251      
594  v20      FR10     217        0.733579                Region  251      
595  v20      FR21     14         0.047328                Region  251      
596  v20      FR22     59         0.199452                Region  251      
597  v20      FR23     42         0.141983                Region  251      
598  v20      FR24     64         0.216355                Region  251      
599  v20      FR25     38         0.128461                Region  251      
600  v20      FR26     39         0.131841                Region  251      
601  v20      FR30     75         0.253541                Region  251      
602  v20      FR41     37         0.125080                Region  251      
603  v20      FR42     51         0.172408                Region  251      
604  v20      FR43     19         0.064230                Region  251      
605  v20      FR51     92         0.311010                Region  251      
606  v20      FR52     106        0.358338                Region  251      
607  v20      FR53     32         0.108178                Region  251      
608  v20      FR61     96         0.324533                Region  251      
609  v20      FR62     110        0.371860             

In [33]:
frequency_train_raw_v3_data[frequency_train_raw_v3_data["Question"]=="v20"]

0      ES12     40         0.135222                Region  251      
581  v20      ES13     20         0.067611                Region  251      
582  v20      ES21     72         0.243399                Region  251      
583  v20      ES22     23         0.077753                Region  251      
584  v20      ES23     16         0.054089                Region  251      
585  v20      ES24     49         0.165647                Region  251      
586  v20      ES30     200        0.676110                Region  251      
587  v20      ES41     85         0.287347                Region  251      
588  v20      ES42     77         0.260302                Region  251      
589  v20      ES43     40         0.135222                Region  251      
590  v20      ES51     201        0.679490                Region  251      
591  v20      ES52     156        0.527366                Region  251      
592  v20      ES53     26         0.087894                Region  251      
593  v20      ES61     287        0.970217                Region  251      
594  v20      ES62     41         0.138602                Region  251      
595  v20      ES63     4          0.013522                Region  251      
596  v20      ES64     4          0.013522                Region  251      
597  v20      ES70     62         0.209594                Region  251      
598  v20      FI193    73         0.246780                Region  251      
599  v20      FI194    74         0.250161                Region  251      
600  v20      FI195    55         0.185930                Region  251      
601  v20      FI196    90         0.304249                Region  251      
602  v20      FI197    149        0.503702                Region  251      
603  v20      FI1B1    423        1.429972                Region  251      
604  v20      FI1C1    137        0.463135                Region  251      
605  v20      FI1C2    52         0.175789                Region  251      
606  v20      FI1C3    58         0.196072                Region  251      
607  v20      FI1C4    67         0.226497                Region  251      
608  v20      FI1C5    35         0.118319                Region  251      
609  v20      FI1D1    38         0.128461                Region  251      
610  v20      FI1D2    88         0.297488                Region  251      
611  v20      FI1D3    50         0.169027                Region  251      
612  v20      FI1D4    33         0.111558                Region  251      
613  v20      FI1D5    23         0.077753                Region  251      
614  v20      FI1D6    123        0.415807                Region  251      
615  v20      FI1D7    61         0.206213                Region  251      
616  v20      FI200    10         0.033805                Region  251      
617  v20      FR10     217        0.733579                Region  251      
618  v20      FR21     14         0.047328                Region  251      
619  v20      FR22     59         0.199452                Region  251      
620  v20      FR23     42         0.141983                Region  251      
621  v20      FR24     64         0.216355                Region  251      
622  v20      FR25     38         0.128461                Region  251      
623  v20      FR26     39         0.131841                Region  251      
624  v20      FR30     75         0.253541                Region  251      
625  v20      FR41     37         0.125080                Region  251      
626  v20      FR42     51         0.172408                Region  251      
627  v20      FR43     19         0.064230                Region  251      
628  v20      FR51     92         0.311010                Region  251      
629  v20      FR52     106        0.358338                Region  251      
630  v20      FR53     32         0.108178                Region  251      
631  v20      FR61     96         0.324533                Region  251      
632  v20      FR62     110        0.371860             

For v20, 3 responses are '99999' in both the raw and preprocessed data. We can ignore this and nothing has to be done for this column

In [34]:
# concerning resposnes: 6, 65, 66, 88, 99
frequency_train_v3_data[frequency_train_v3_data["Question"]=="v25"]

Question Response  Frequency  Relative Frequency (%)        Label  Unique  \
745  v25      65       138        0.466516                Citizenship  130      
746  v25      66       28051      94.827761               Citizenship  130      
747  v25      88       17         0.057469                Citizenship  130      
748  v25      99       117        0.395524                Citizenship  130      
749  v25      AF       6          0.020283                Citizenship  130      
750  v25      AL       2          0.006761                Citizenship  130      
751  v25      AM       1          0.003381                Citizenship  130      
752  v25      AO       3          0.010142                Citizenship  130      
753  v25      AR       3          0.010142                Citizenship  130      
754  v25      AT       14         0.047328                Citizenship  130      
755  v25      AU       2          0.006761                Citizenship  130      
756  v25      BA       29         0.098036                Citizenship  130      
757  v25      BD       4          0.013522                Citizenship  130      
758  v25      BE       13         0.043947                Citizenship  130      
759  v25      BF       1          0.003381                Citizenship  130      
760  v25      BG       6          0.020283                Citizenship  130      
761  v25      BJ       1          0.003381                Citizenship  130      
762  v25      BO       4          0.013522                Citizenship  130      
763  v25      BR       22         0.074372                Citizenship  130      
764  v25      BY       6          0.020283                Citizenship  130      
765  v25      CA       5          0.016903                Citizenship  130      
766  v25      CD       4          0.013522                Citizenship  130      
767  v25      CG       3          0.010142                Citizenship  130      
768  v25      CH       1          0.003381                Citizenship  130      
769  v25      CI       2          0.006761                Citizenship  130      
770  v25      CL       3          0.010142                Citizenship  130      
771  v25      CM       2          0.006761                Citizenship  130      
772  v25      CN       11         0.037186                Citizenship  130      
773  v25      CO       5          0.016903                Citizenship  130      
774  v25      CU       2          0.006761                Citizenship  130      
775  v25      CV       2          0.006761                Citizenship  130      
776  v25      CZ       6          0.020283                Citizenship  130      
777  v25      DE       93         0.314391                Citizenship  130      
778  v25      DK       8          0.027044                Citizenship  130      
779  v25      DO       2          0.006761                Citizenship  130      
780  v25      DZ       16         0.054089                Citizenship  130      
781  v25      EE       15         0.050708                Citizenship  130      
782  v25      EG       3          0.010142                Citizenship  130      
783  v25      ER       1          0.003381                Citizenship  130      
784  v25      ES       19         0.064230                Citizenship  130      
785  v25      ET       1          0.003381                Citizenship  130      
786  v25      FI       11         0.037186                Citizenship  130      
787  v25      FR       28         0.094655                Citizenship  130      
788  v25      GA       1          0.003381                Citizenship  130      
789  v25      GB       59         0.199452                Citizenship  130      
790  v25      GD       1          0.003381                Citizenship  130      
791  v25      GE       1          0.003381                Citizenship  130      
792  v25      GH       1          0.003381                Citizenship  130      
793  v25      GM       2          0

In [35]:
frequency_train_raw_v3_data[frequency_train_raw_v3_data["Question"]=="v25"]

Question Response  Frequency  Relative Frequency (%)        Label  Unique  \
772  v25      65       138        0.466516                Citizenship  130      
773  v25      66       28051      94.827761               Citizenship  130      
774  v25      88       17         0.057469                Citizenship  130      
775  v25      99       117        0.395524                Citizenship  130      
776  v25      AF       6          0.020283                Citizenship  130      
777  v25      AL       2          0.006761                Citizenship  130      
778  v25      AM       1          0.003381                Citizenship  130      
779  v25      AO       3          0.010142                Citizenship  130      
780  v25      AR       3          0.010142                Citizenship  130      
781  v25      AT       14         0.047328                Citizenship  130      
782  v25      AU       2          0.006761                Citizenship  130      
783  v25      BA       29         0.098036                Citizenship  130      
784  v25      BD       4          0.013522                Citizenship  130      
785  v25      BE       13         0.043947                Citizenship  130      
786  v25      BF       1          0.003381                Citizenship  130      
787  v25      BG       6          0.020283                Citizenship  130      
788  v25      BJ       1          0.003381                Citizenship  130      
789  v25      BO       4          0.013522                Citizenship  130      
790  v25      BR       22         0.074372                Citizenship  130      
791  v25      BY       6          0.020283                Citizenship  130      
792  v25      CA       5          0.016903                Citizenship  130      
793  v25      CD       4          0.013522                Citizenship  130      
794  v25      CG       3          0.010142                Citizenship  130      
795  v25      CH       1          0.003381                Citizenship  130      
796  v25      CI       2          0.006761                Citizenship  130      
797  v25      CL       3          0.010142                Citizenship  130      
798  v25      CM       2          0.006761                Citizenship  130      
799  v25      CN       11         0.037186                Citizenship  130      
800  v25      CO       5          0.016903                Citizenship  130      
801  v25      CU       2          0.006761                Citizenship  130      
802  v25      CV       2          0.006761                Citizenship  130      
803  v25      CZ       6          0.020283                Citizenship  130      
804  v25      DE       93         0.314391                Citizenship  130      
805  v25      DK       8          0.027044                Citizenship  130      
806  v25      DO       2          0.006761                Citizenship  130      
807  v25      DZ       16         0.054089                Citizenship  130      
808  v25      EE       15         0.050708                Citizenship  130      
809  v25      EG       3          0.010142                Citizenship  130      
810  v25      ER       1          0.003381                Citizenship  130      
811  v25      ES       19         0.064230                Citizenship  130      
812  v25      ET       1          0.003381                Citizenship  130      
813  v25      FI       11         0.037186                Citizenship  130      
814  v25      FR       28         0.094655                Citizenship  130      
815  v25      GA       1          0.003381                Citizenship  130      
816  v25      GB       59         0.199452                Citizenship  130      
817  v25      GD       1          0.003381                Citizenship  130      
818  v25      GE       1          0.003381                Citizenship  130      
819  v25      GH       1          0.003381                Citizenship  130      
820  v25      GM       2          0

For v25, 95% of responses are '66' for 'Citizenship' in both the raw and preprocessed data. Will just leave this column in there since its not a preprocessing error - maybe drop this column if there is another variable that is highly correlated with this

In [36]:
# concerning responses: 2, 3, 4, 6, 66, 77, 88, 99
frequency_train_v3_data[frequency_train_v3_data["Question"]=="v78"]

Question Response  Frequency  Relative Frequency (%)  \
1144  v78      2        37         0.125080                 
1145  v78      3        20         0.067611                 
1146  v78      4        31         0.104797                 
1147  v78      66       24508      82.850478                
1148  v78      77       2          0.006761                 
1149  v78      88       41         0.138602                 
1150  v78      99       189        0.638924                 
1151  v78      AF       16         0.054089                 
1152  v78      AG       1          0.003381                 
1153  v78      AL       6          0.020283                 
1154  v78      AM       6          0.020283                 
1155  v78      AO       10         0.033805                 
1156  v78      AR       18         0.060850                 
1157  v78      AT       55         0.185930                 
1158  v78      AU       6          0.020283                 
1159  v78      AW       4          0.013522                 
1160  v78      AX       1          0.003381                 
1161  v78      AZ       8          0.027044                 
1162  v78      BA       111        0.375241                 
1163  v78      BD       4          0.013522                 
1164  v78      BE       28         0.094655                 
1165  v78      BF       1          0.003381                 
1166  v78      BG       39         0.131841                 
1167  v78      BI       1          0.003381                 
1168  v78      BJ       2          0.006761                 
1169  v78      BO       4          0.013522                 
1170  v78      BQ       1          0.003381                 
1171  v78      BR       38         0.128461                 
1172  v78      BY       108        0.365099                 
1173  v78      CA       10         0.033805                 
1174  v78      CD       5          0.016903                 
1175  v78      CF       1          0.003381                 
1176  v78      CG       4          0.013522                 
1177  v78      CH       8          0.027044                 
1178  v78      CI       4          0.013522                 
1179  v78      CL       15         0.050708                 
1180  v78      CM       2          0.006761                 
1181  v78      CN       28         0.094655                 
1182  v78      CO       14         0.047328                 
1183  v78      CR       1          0.003381                 
1184  v78      CU       10         0.033805                 
1185  v78      CV       11         0.037186                 
1186  v78      CW       5          0.016903                 
1187  v78      CY       1          0.003381                 
1188  v78      CZ       44         0.148744                 
1189  v78      DE       211        0.713296                 
1190  v78      DK       23         0.077753                 
1191  v78      DO       5          0.016903                 
1192  v78      DZ       83         0.280586                 
1193  v78      EC       8          0.027044                 
1194  v78      EE       15         0.050708                 
1195  v78      EG       23         0.077753                 
1196  v78      ER       4          0.013522                 
1197  v78      ES       51         0.172408                 
1198  v78      ET       37         0.125080                 
1199  v78      FI       48         0.162266                 
1200  v78      FO       4          0.013522                 
1201  v78      FR       71         0.240019                 
1202  v78      GA       1          0.003381                 
1203  v78      GB       107        0.361719                 
1204  v78      GD       1          0.003381                 
1205  v78      GE       14         0.047328                 
1206  v78      GH       5          0.016903                 
1207  v78      GL       2          0.006761                 
1208  v78      GM       2          0.006

In [37]:
frequency_train_raw_v3_data[frequency_train_raw_v3_data["Question"]=="v78"]

Question Response  Frequency  Relative Frequency (%)  \
1219  v78      2        37         0.125080                 
1220  v78      3        20         0.067611                 
1221  v78      4        31         0.104797                 
1222  v78      66       24508      82.850478                
1223  v78      77       2          0.006761                 
1224  v78      88       41         0.138602                 
1225  v78      99       189        0.638924                 
1226  v78      AF       16         0.054089                 
1227  v78      AG       1          0.003381                 
1228  v78      AL       6          0.020283                 
1229  v78      AM       6          0.020283                 
1230  v78      AO       10         0.033805                 
1231  v78      AR       18         0.060850                 
1232  v78      AT       55         0.185930                 
1233  v78      AU       6          0.020283                 
1234  v78      AW       4          0.013522                 
1235  v78      AX       1          0.003381                 
1236  v78      AZ       8          0.027044                 
1237  v78      BA       111        0.375241                 
1238  v78      BD       4          0.013522                 
1239  v78      BE       28         0.094655                 
1240  v78      BF       1          0.003381                 
1241  v78      BG       39         0.131841                 
1242  v78      BI       1          0.003381                 
1243  v78      BJ       2          0.006761                 
1244  v78      BO       4          0.013522                 
1245  v78      BQ       1          0.003381                 
1246  v78      BR       38         0.128461                 
1247  v78      BY       108        0.365099                 
1248  v78      CA       10         0.033805                 
1249  v78      CD       5          0.016903                 
1250  v78      CF       1          0.003381                 
1251  v78      CG       4          0.013522                 
1252  v78      CH       8          0.027044                 
1253  v78      CI       4          0.013522                 
1254  v78      CL       15         0.050708                 
1255  v78      CM       2          0.006761                 
1256  v78      CN       28         0.094655                 
1257  v78      CO       14         0.047328                 
1258  v78      CR       1          0.003381                 
1259  v78      CU       10         0.033805                 
1260  v78      CV       11         0.037186                 
1261  v78      CW       5          0.016903                 
1262  v78      CY       1          0.003381                 
1263  v78      CZ       44         0.148744                 
1264  v78      DE       211        0.713296                 
1265  v78      DK       23         0.077753                 
1266  v78      DO       5          0.016903                 
1267  v78      DZ       83         0.280586                 
1268  v78      EC       8          0.027044                 
1269  v78      EE       15         0.050708                 
1270  v78      EG       23         0.077753                 
1271  v78      ER       4          0.013522                 
1272  v78      ES       51         0.172408                 
1273  v78      ET       37         0.125080                 
1274  v78      FI       48         0.162266                 
1275  v78      FO       4          0.013522                 
1276  v78      FR       71         0.240019                 
1277  v78      GA       1          0.003381                 
1278  v78      GB       107        0.361719                 
1279  v78      GD       1          0.003381                 
1280  v78      GE       14         0.047328                 
1281  v78      GH       5          0.016903                 
1282  v78      GL       2          0.006761                 
1283  v78      GM       2          0.006

For v78, 83% of responses are '66' for 'Country of birth, father' in both the raw and preprocessed data. Will just leave this column in there since its not a preprocessing error - maybe drop this column if there is another variable that is highly correlated with this

In [38]:
# concerning responses: 777, 888, 999
frequency_train_v3_data[frequency_train_v3_data["Question"]=="v154"]

Question Response  Frequency  Relative Frequency (%)  \
2646  v154     777      11         0.037186                 
2647  v154     888      45         0.152125                 
2648  v154     999      171        0.578074                 
2649  v154     ABK      1          0.003381                 
2650  v154     AKA      1          0.003381                 
2651  v154     ALB      31         0.104797                 
2652  v154     AMH      16         0.054089                 
2653  v154     APA      15         0.050708                 
2654  v154     ARA      448        1.514486                 
2655  v154     ARM      9          0.030425                 
2656  v154     AST      1          0.003381                 
2657  v154     AZE      2          0.006761                 
2658  v154     BAM      1          0.003381                 
2659  v154     BAQ      23         0.077753                 
2660  v154     BEL      1          0.003381                 
2661  v154     BEN      3          0.010142                 
2662  v154     BER      4          0.013522                 
2663  v154     BOS      33         0.111558                 
2664  v154     BUL      3          0.010142                 
2665  v154     CAT      142        0.480038                 
2666  v154     CHI      12         0.040567                 
2667  v154     CPF      1          0.003381                 
2668  v154     CPP      6          0.020283                 
2669  v154     CZE      1579       5.337886                 
2670  v154     DAN      1149       3.884250                 
2671  v154     DUT      1408       4.759812                 
2672  v154     EGY      1          0.003381                 
2673  v154     ENG      3461       11.700078                
2674  v154     EST      1001       3.383929                 
2675  v154     FAO      1          0.003381                 
2676  v154     FIL      1          0.003381                 
2677  v154     FIN      1524       5.151956                 
2678  v154     FRE      1692       5.719888                 
2679  v154     FRM      6          0.020283                 
2680  v154     FRO      1          0.003381                 
2681  v154     FRS      32         0.108178                 
2682  v154     GEM      8          0.027044                 
2683  v154     GEO      1          0.003381                 
2684  v154     GER      3608       12.197018                
2685  v154     GLE      10         0.033805                 
2686  v154     GLG      55         0.185930                 
2687  v154     GRE      6          0.020283                 
2688  v154     GSW      686        2.319056                 
2689  v154     GUJ      8          0.027044                 
2690  v154     HEB      1331       4.499510                 
2691  v154     HIN      11         0.037186                 
2692  v154     HRV      22         0.074372                 
2693  v154     HUN      1150       3.887631                 
2694  v154     ICE      1          0.003381                 
2695  v154     IND      1          0.003381                 
2696  v154     IRA      9          0.030425                 
2697  v154     ITA      67         0.226497                 
2698  v154     JPN      1          0.003381                 
2699  v154     KAB      1          0.003381                 
2700  v154     KUR      23         0.077753                 
2701  v154     LAO      1          0.003381                 
2702  v154     LAV      3          0.010142                 
2703  v154     LIN      1          0.003381                 
2704  v154     LIT      1520       5.138433                 
2705  v154     MAL      3          0.010142                 
2706  v154     MAN      2          0.006761                 
2707  v154     MAY      2          0.006761                 
2708  v154     MIS      3          0.010142                 
2709  v154     MLG      2          0.006761                 
2710  v154     MON      1          0.003

In [39]:
frequency_train_raw_v3_data[frequency_train_raw_v3_data["Question"]=="v154"]

Question Response  Frequency  Relative Frequency (%)  \
2838  v154     777      11         0.037186                 
2839  v154     888      45         0.152125                 
2840  v154     999      171        0.578074                 
2841  v154     ABK      1          0.003381                 
2842  v154     AKA      1          0.003381                 
2843  v154     ALB      31         0.104797                 
2844  v154     AMH      16         0.054089                 
2845  v154     APA      15         0.050708                 
2846  v154     ARA      448        1.514486                 
2847  v154     ARM      9          0.030425                 
2848  v154     AST      1          0.003381                 
2849  v154     AZE      2          0.006761                 
2850  v154     BAM      1          0.003381                 
2851  v154     BAQ      23         0.077753                 
2852  v154     BEL      1          0.003381                 
2853  v154     BEN      3          0.010142                 
2854  v154     BER      4          0.013522                 
2855  v154     BOS      33         0.111558                 
2856  v154     BUL      3          0.010142                 
2857  v154     CAT      142        0.480038                 
2858  v154     CHI      12         0.040567                 
2859  v154     CPF      1          0.003381                 
2860  v154     CPP      6          0.020283                 
2861  v154     CZE      1579       5.337886                 
2862  v154     DAN      1149       3.884250                 
2863  v154     DUT      1408       4.759812                 
2864  v154     EGY      1          0.003381                 
2865  v154     ENG      3461       11.700078                
2866  v154     EST      1001       3.383929                 
2867  v154     FAO      1          0.003381                 
2868  v154     FIL      1          0.003381                 
2869  v154     FIN      1524       5.151956                 
2870  v154     FRE      1692       5.719888                 
2871  v154     FRM      6          0.020283                 
2872  v154     FRO      1          0.003381                 
2873  v154     FRS      32         0.108178                 
2874  v154     GEM      8          0.027044                 
2875  v154     GEO      1          0.003381                 
2876  v154     GER      3608       12.197018                
2877  v154     GLE      10         0.033805                 
2878  v154     GLG      55         0.185930                 
2879  v154     GRE      6          0.020283                 
2880  v154     GSW      686        2.319056                 
2881  v154     GUJ      8          0.027044                 
2882  v154     HEB      1331       4.499510                 
2883  v154     HIN      11         0.037186                 
2884  v154     HRV      22         0.074372                 
2885  v154     HUN      1150       3.887631                 
2886  v154     ICE      1          0.003381                 
2887  v154     IND      1          0.003381                 
2888  v154     IRA      9          0.030425                 
2889  v154     ITA      67         0.226497                 
2890  v154     JPN      1          0.003381                 
2891  v154     KAB      1          0.003381                 
2892  v154     KUR      23         0.077753                 
2893  v154     LAO      1          0.003381                 
2894  v154     LAV      3          0.010142                 
2895  v154     LIN      1          0.003381                 
2896  v154     LIT      1520       5.138433                 
2897  v154     MAL      3          0.010142                 
2898  v154     MAN      2          0.006761                 
2899  v154     MAY      2          0.006761                 
2900  v154     MIS      3          0.010142                 
2901  v154     MLG      2          0.006761                 
2902  v154     MON      1          0.003

For v154, less than 1% of responses are 777, 888, 999. We can ignore this and nothing has to be done with this column

In [40]:
# concerning responses: 0, 777, 888, 999
frequency_train_v3_data[frequency_train_v3_data["Question"]=="v155"]

Question Response  Frequency  Relative Frequency (%)  \
2752  v155     0        23485      79.392177                
2753  v155     777      12         0.040567                 
2754  v155     888      26         0.087894                 
2755  v155     999      1729       5.844968                 
2756  v155     ALB      15         0.050708                 
2757  v155     AMH      15         0.050708                 
2758  v155     APA      5          0.016903                 
2759  v155     ARA      119        0.402285                 
2760  v155     ARM      1          0.003381                 
2761  v155     BAQ      14         0.047328                 
2762  v155     BEL      4          0.013522                 
2763  v155     BEN      1          0.003381                 
2764  v155     BER      2          0.006761                 
2765  v155     BOS      22         0.074372                 
2766  v155     BRE      2          0.006761                 
2767  v155     BUL      8          0.027044                 
2768  v155     CAD      1          0.003381                 
2769  v155     CAT      67         0.226497                 
2770  v155     CHI      8          0.027044                 
2771  v155     CPF      11         0.037186                 
2772  v155     CPP      3          0.010142                 
2773  v155     CSB      1          0.003381                 
2774  v155     CZE      12         0.040567                 
2775  v155     DAN      499        1.686894                 
2776  v155     DUT      53         0.179169                 
2777  v155     DYU      2          0.006761                 
2778  v155     ENG      825        2.788952                 
2779  v155     ENM      1          0.003381                 
2780  v155     EST      6          0.020283                 
2781  v155     EWE      1          0.003381                 
2782  v155     FAO      2          0.006761                 
2783  v155     FIL      1          0.003381                 
2784  v155     FIN      36         0.121700                 
2785  v155     FON      1          0.003381                 
2786  v155     FRE      233        0.787668                 
2787  v155     FRM      1          0.003381                 
2788  v155     FRO      1          0.003381                 
2789  v155     FRS      12         0.040567                 
2790  v155     GEM      39         0.131841                 
2791  v155     GEO      3          0.010142                 
2792  v155     GER      357        1.206856                 
2793  v155     GLE      153        0.517224                 
2794  v155     GLG      44         0.148744                 
2795  v155     GRE      8          0.027044                 
2796  v155     GRN      1          0.003381                 
2797  v155     GSW      91         0.307630                 
2798  v155     GUJ      1          0.003381                 
2799  v155     HAT      1          0.003381                 
2800  v155     HEB      308        1.041209                 
2801  v155     HER      1          0.003381                 
2802  v155     HIN      5          0.016903                 
2803  v155     HRV      37         0.125080                 
2804  v155     HUN      22         0.074372                 
2805  v155     HUP      1          0.003381                 
2806  v155     IBO      2          0.006761                 
2807  v155     IND      2          0.006761                 
2808  v155     IRA      1          0.003381                 
2809  v155     ITA      125        0.422569                 
2810  v155     JPN      3          0.010142                 
2811  v155     KIK      1          0.003381                 
2812  v155     KIN      1          0.003381                 
2813  v155     KON      1          0.003381                 
2814  v155     KUR      5          0.016903                 
2815  v155     LAV      5          0.016903                 
2816  v155     LIN      5          0.016

In [41]:
frequency_train_raw_v3_data[frequency_train_raw_v3_data["Question"]=="v155"]

Question Response  Frequency  Relative Frequency (%)  \
2944  v155     0        23485      79.392177                
2945  v155     777      12         0.040567                 
2946  v155     888      26         0.087894                 
2947  v155     999      1729       5.844968                 
2948  v155     ALB      15         0.050708                 
2949  v155     AMH      15         0.050708                 
2950  v155     APA      5          0.016903                 
2951  v155     ARA      119        0.402285                 
2952  v155     ARM      1          0.003381                 
2953  v155     BAQ      14         0.047328                 
2954  v155     BEL      4          0.013522                 
2955  v155     BEN      1          0.003381                 
2956  v155     BER      2          0.006761                 
2957  v155     BOS      22         0.074372                 
2958  v155     BRE      2          0.006761                 
2959  v155     BUL      8          0.027044                 
2960  v155     CAD      1          0.003381                 
2961  v155     CAT      67         0.226497                 
2962  v155     CHI      8          0.027044                 
2963  v155     CPF      11         0.037186                 
2964  v155     CPP      3          0.010142                 
2965  v155     CSB      1          0.003381                 
2966  v155     CZE      12         0.040567                 
2967  v155     DAN      499        1.686894                 
2968  v155     DUT      53         0.179169                 
2969  v155     DYU      2          0.006761                 
2970  v155     ENG      825        2.788952                 
2971  v155     ENM      1          0.003381                 
2972  v155     EST      6          0.020283                 
2973  v155     EWE      1          0.003381                 
2974  v155     FAO      2          0.006761                 
2975  v155     FIL      1          0.003381                 
2976  v155     FIN      36         0.121700                 
2977  v155     FON      1          0.003381                 
2978  v155     FRE      233        0.787668                 
2979  v155     FRM      1          0.003381                 
2980  v155     FRO      1          0.003381                 
2981  v155     FRS      12         0.040567                 
2982  v155     GEM      39         0.131841                 
2983  v155     GEO      3          0.010142                 
2984  v155     GER      357        1.206856                 
2985  v155     GLE      153        0.517224                 
2986  v155     GLG      44         0.148744                 
2987  v155     GRE      8          0.027044                 
2988  v155     GRN      1          0.003381                 
2989  v155     GSW      91         0.307630                 
2990  v155     GUJ      1          0.003381                 
2991  v155     HAT      1          0.003381                 
2992  v155     HEB      308        1.041209                 
2993  v155     HER      1          0.003381                 
2994  v155     HIN      5          0.016903                 
2995  v155     HRV      37         0.125080                 
2996  v155     HUN      22         0.074372                 
2997  v155     HUP      1          0.003381                 
2998  v155     IBO      2          0.006761                 
2999  v155     IND      2          0.006761                 
3000  v155     IRA      1          0.003381                 
3001  v155     ITA      125        0.422569                 
3002  v155     JPN      3          0.010142                 
3003  v155     KIK      1          0.003381                 
3004  v155     KIN      1          0.003381                 
3005  v155     KON      1          0.003381                 
3006  v155     KUR      5          0.016903                 
3007  v155     LAV      5          0.016903                 
3008  v155     LIN      5          0.016

For v155, the question is "Language most often spoken at home: second mentioned" and 80% of responses are 0 which I am interpreting as Not Applicable. Will just leave this column in there since its not a preprocessing error

In [42]:
# concerncing responses: 2, 3, 4, 66, 77, 88, 99
frequency_train_v3_data[frequency_train_v3_data["Question"]=="v161"]

Question Response  Frequency  Relative Frequency (%)  \
2899  v161     2        38         0.128461                 
2900  v161     3        18         0.060850                 
2901  v161     4        23         0.077753                 
2902  v161     66       24739      83.631385                
2903  v161     77       3          0.010142                 
2904  v161     88       32         0.108178                 
2905  v161     99       184        0.622021                 
2906  v161     AD       1          0.003381                 
2907  v161     AF       17         0.057469                 
2908  v161     AL       5          0.016903                 
2909  v161     AM       5          0.016903                 
2910  v161     AO       12         0.040567                 
2911  v161     AR       31         0.104797                 
2912  v161     AT       57         0.192691                 
2913  v161     AU       8          0.027044                 
2914  v161     AW       3          0.010142                 
2915  v161     AX       1          0.003381                 
2916  v161     AZ       7          0.023664                 
2917  v161     BA       105        0.354958                 
2918  v161     BD       4          0.013522                 
2919  v161     BE       32         0.108178                 
2920  v161     BF       1          0.003381                 
2921  v161     BG       33         0.111558                 
2922  v161     BI       1          0.003381                 
2923  v161     BJ       2          0.006761                 
2924  v161     BO       5          0.016903                 
2925  v161     BQ       1          0.003381                 
2926  v161     BR       37         0.125080                 
2927  v161     BY       103        0.348196                 
2928  v161     CA       6          0.020283                 
2929  v161     CD       6          0.020283                 
2930  v161     CF       1          0.003381                 
2931  v161     CG       4          0.013522                 
2932  v161     CH       9          0.030425                 
2933  v161     CI       6          0.020283                 
2934  v161     CL       13         0.043947                 
2935  v161     CM       2          0.006761                 
2936  v161     CN       26         0.087894                 
2937  v161     CO       15         0.050708                 
2938  v161     CR       1          0.003381                 
2939  v161     CU       8          0.027044                 
2940  v161     CV       10         0.033805                 
2941  v161     CW       5          0.016903                 
2942  v161     CZ       39         0.131841                 
2943  v161     DE       231        0.780907                 
2944  v161     DK       18         0.060850                 
2945  v161     DO       5          0.016903                 
2946  v161     DZ       69         0.233258                 
2947  v161     EC       10         0.033805                 
2948  v161     EE       16         0.054089                 
2949  v161     EG       27         0.091275                 
2950  v161     ER       3          0.010142                 
2951  v161     ES       50         0.169027                 
2952  v161     ET       39         0.131841                 
2953  v161     FI       57         0.192691                 
2954  v161     FO       4          0.013522                 
2955  v161     FR       63         0.212975                 
2956  v161     GA       1          0.003381                 
2957  v161     GB       119        0.402285                 
2958  v161     GD       1          0.003381                 
2959  v161     GE       18         0.060850                 
2960  v161     GH       3          0.010142                 
2961  v161     GI       1          0.003381                 
2962  v161     GL       2          0.006761                 
2963  v161     GM       2          0.006

In [43]:
frequency_train_raw_v3_data[frequency_train_raw_v3_data["Question"]=="v161"]

Question Response  Frequency  Relative Frequency (%)  \
3098  v161     2        38         0.128461                 
3099  v161     3        18         0.060850                 
3100  v161     4        23         0.077753                 
3101  v161     66       24739      83.631385                
3102  v161     77       3          0.010142                 
3103  v161     88       32         0.108178                 
3104  v161     99       184        0.622021                 
3105  v161     AD       1          0.003381                 
3106  v161     AF       17         0.057469                 
3107  v161     AL       5          0.016903                 
3108  v161     AM       5          0.016903                 
3109  v161     AO       12         0.040567                 
3110  v161     AR       31         0.104797                 
3111  v161     AT       57         0.192691                 
3112  v161     AU       8          0.027044                 
3113  v161     AW       3          0.010142                 
3114  v161     AX       1          0.003381                 
3115  v161     AZ       7          0.023664                 
3116  v161     BA       105        0.354958                 
3117  v161     BD       4          0.013522                 
3118  v161     BE       32         0.108178                 
3119  v161     BF       1          0.003381                 
3120  v161     BG       33         0.111558                 
3121  v161     BI       1          0.003381                 
3122  v161     BJ       2          0.006761                 
3123  v161     BO       5          0.016903                 
3124  v161     BQ       1          0.003381                 
3125  v161     BR       37         0.125080                 
3126  v161     BY       103        0.348196                 
3127  v161     CA       6          0.020283                 
3128  v161     CD       6          0.020283                 
3129  v161     CF       1          0.003381                 
3130  v161     CG       4          0.013522                 
3131  v161     CH       9          0.030425                 
3132  v161     CI       6          0.020283                 
3133  v161     CL       13         0.043947                 
3134  v161     CM       2          0.006761                 
3135  v161     CN       26         0.087894                 
3136  v161     CO       15         0.050708                 
3137  v161     CR       1          0.003381                 
3138  v161     CU       8          0.027044                 
3139  v161     CV       10         0.033805                 
3140  v161     CW       5          0.016903                 
3141  v161     CZ       39         0.131841                 
3142  v161     DE       231        0.780907                 
3143  v161     DK       18         0.060850                 
3144  v161     DO       5          0.016903                 
3145  v161     DZ       69         0.233258                 
3146  v161     EC       10         0.033805                 
3147  v161     EE       16         0.054089                 
3148  v161     EG       27         0.091275                 
3149  v161     ER       3          0.010142                 
3150  v161     ES       50         0.169027                 
3151  v161     ET       39         0.131841                 
3152  v161     FI       57         0.192691                 
3153  v161     FO       4          0.013522                 
3154  v161     FR       63         0.212975                 
3155  v161     GA       1          0.003381                 
3156  v161     GB       119        0.402285                 
3157  v161     GD       1          0.003381                 
3158  v161     GE       18         0.060850                 
3159  v161     GH       3          0.010142                 
3160  v161     GI       1          0.003381                 
3161  v161     GL       2          0.006761                 
3162  v161     GM       2          0.006

For v161, 84% of responses are '66' for 'Country of birth, mother' in both the raw and preprocessed data. Will just leave this column in there since its not a preprocessing error - maybe drop this column if there is another variable that is highly correlated with this

In [44]:
# concerncing responses: none
frequency_train_v3_data[frequency_train_v3_data["Question"]=="cntry"]

Question Response  Frequency  Relative Frequency (%)    Label  Unique  \
3997  cntry    AT       1384       4.678679                Country  21       
3998  cntry    BE       9          0.030425                Country  21       
3999  cntry    CH       1186       4.009330                Country  21       
4000  cntry    CZ       1603       5.419019                Country  21       
4001  cntry    DE       2377       8.035563                Country  21       
4002  cntry    DK       1189       4.019472                Country  21       
4003  cntry    EE       1592       5.381833                Country  21       
4004  cntry    ES       1511       5.108009                Country  21       
4005  cntry    FI       1639       5.540719                Country  21       
4006  cntry    FR       1498       5.064061                Country  21       
4007  cntry    GB       1741       5.885535                Country  21       
4008  cntry    HU       1187       4.012711                Country  21       
4009  cntry    IE       1826       6.172881                Country  21       
4010  cntry    IL       1956       6.612353                Country  21       
4011  cntry    LT       1707       5.770596                Country  21       
4012  cntry    NL       1485       5.020114                Country  21       
4013  cntry    NO       1128       3.813259                Country  21       
4014  cntry    PL       1240       4.191880                Country  21       
4015  cntry    PT       978        3.306176                Country  21       
4016  cntry    SE       1419       4.796998                Country  21       
4017  cntry    SI       926        3.130388                Country  21       

     Type_codebook_long  
3997  string             
3998  string             
3999  string             
4000  string             
4001  string             
4002  string             
4003  string             
4004  string             
4005  string             
4006  string             
4007  string             
4008  string             
4009  string             
4010  string             
4011  string             
4012  string             
4013  string             
4014  string             
4015  string             
4016  string             
4017  string

Lets convert all non-categorical variables to int64

In [61]:
num_cols = train_v3.loc[:, ~train_v3.columns.isin(cat_cols)].columns.tolist()
num_df = train_v3[num_cols]

train_v3[num_cols] = train_v3[num_cols].astype("int64")

### Correlation Analysis
<a id="Correlation-Analysis"></a>

We will leave all variables/columns in the data set for now. 

Once we get to the logistic regression modelling stage, we may decide to remove highly correlated variables/columns.

In [63]:
def get_redundant_pairs(df):
    pairs_to_drop = set()
    cols = df.columns
    for i in range(0, df.shape[1]):
        for j in range(0,i+1):
            pairs_to_drop.add((cols[i], cols[j]))
    return pairs_to_drop

def get_top_abs_correlations(df, n=5):
    au_corr = df.corr().abs().unstack()
    labels_to_drop = get_redundant_pairs(df)
    au_corr = au_corr.drop(labels=labels_to_drop).sort_values(ascending=False)
    return au_corr[0:n]

corr_df = get_top_abs_correlations(num_df, 30).to_frame().reset_index().rename(columns={0: "abs_corr"})
corr_df = corr_df.merge(codebook[['Variable', "Label"]], left_on = 'level_0', right_on = "Variable", how = "left").drop("Variable", axis = 1).rename(columns = {"Label":"label_0"})
corr_df = corr_df.merge(codebook[['Variable', "Label"]], left_on = 'level_1', right_on = "Variable", how = "left").drop("Variable", axis = 1).rename(columns = {"Label":"label_1"})
corr_df

level_0 level_1  abs_corr                            label_0  \
0   v128    v129    0.998918  End of interview, month             
1   v124    v125    0.996732  End of interview, day of month      
2   v196    v208    0.994988  Second person in household: re...   
3   v125    v228    0.992443  Start of interview, day of month    
4   v124    v228    0.991285  End of interview, day of month      
5   v57     v65     0.991019  Highest level of education          
6   v102    v103    0.990104  Main source of household income     
7   v58     v66     0.989397  Father's highest level of educ...   
8   v59     v66     0.989349  Father's highest level of educ...   
9   v60     v67     0.987533  Mother's highest level of educ...   
10  v129    v229    0.986330  Start of interview, month           
11  v128    v229    0.985418  End of interview, month             
12  v61     v67     0.984809  Mother's highest level of educ...   
13  v58     v59     0.982577  Father's highest level of educ...   
14  v126    v130    0.980389  End of interview, hour              
15  v56     v65     0.979479  Highest level of education          
16  v60     v61     0.978971  Mother's highest level of educ...   
17  v56     v57     0.978950  Highest level of education          
18  v30     v171    0.973798  Partner doing last 7 days: not...   
19  v90     v263    0.887262  Gender of second person in hou...   
20  v108    v254    0.873407  Have a set 'basic' or contract...   
21  v235    v237    0.844856  Trust in politicians                
22  v129    v134    0.818034  Start of interview, month           
23  v128    v134    0.816976  End of interview, month             
24  v134    v229    0.804547  Start of interview, year            
25  v163    v175    0.800469  Main activity, last 7 days. Al...   
26  v70     v108    0.796531  Employment relation                 
27  v152    v254    0.795367  Responsible for supervising ot...   
28  v108    v152    0.770473  Have a set 'basic' or contract...   
29  v70     v254    0.762870  Employment relation                 

                              label_1  
0   Start of interview, month          
1   Start of interview, day of month   
2   Second person in household: re...  
3   Day of month, supplementary qu...  
4   Day of month, supplementary qu...  
5   Highest level of education, ES...  
6   Main source of household income    
7   Father's highest level of educ...  
8   Father's highest level of educ...  
9   Mother's highest level of educ...  
10  Month, supplementary questionn...  
11  Month, supplementary questionn...  
12  Mother's highest level of educ...  
13  Father's highest level of educ...  
14  Start of interview, hour           
15  Highest level of education, ES...  
16  Mother's highest level of educ...  
17  Highest level of education         
18  Lives with husband/wife/partne...  
19  Year of birth of second person...  
20  Paid work in another country, ...  
21  Trust in political parties         
22  Start of interview, year           
23  Start of interview, year           
24  Month, supplementary questionn...  
25  Doing last 7 days: paid work       
26  Have a set 'basic' or contract...  
27  Paid work in another country, ...  
28  Responsible for supervising ot...  
29  Paid work in another country, ...

Isolating high correlations with the target variable

In [66]:
corr_matrix = num_df.corr()

print("Top positive correlations with target")
pos_corr = pd.DataFrame(corr_matrix["satisfied"].sort_values(ascending=False)[0:10])
pos_corr.merge(codebook[codebook_labels], left_index = True, right_on = "Variable", how = "left")

Top positive correlations with target


satisfied   Variable                              Label
272  1.000000   satisfied  Target                           
97   0.550926   v98        How happy are you                
223  0.329335   v224       How satisfied with present sta...
73   0.326110   v74        Enjoyed life, how often past week
252  0.319583   v253       Were happy, how often past week  
222  0.271414   v223       How satisfied with the way dem...
177  0.249736   v178       Most people try to take advant...
179  0.248674   v180       Most people can be trusted or ...
232  0.235256   v233       Trust in the legal system        
225  0.230834   v226       How satisfied with the nationa...

In [67]:
print("Top negative correlations with target")
neg_corr = pd.DataFrame(corr_matrix["satisfied"].sort_values(ascending=True)[0:10])
neg_corr.merge(codebook[codebook_labels], left_index = True, right_on = "Variable", how = "left")

Top negative correlations with target


satisfied Variable                              Label
100 -0.321658   v101     Feeling about household's inco...
78  -0.295399   v79      Felt depressed, how often past...
98  -0.277019   v99      Subjective general health        
81  -0.267112   v82      Felt sad, how often past week    
80  -0.236721   v81      Felt lonely, how often past week 
79  -0.204854   v80      Felt everything did as effort,...
12  -0.201093   v13      Could not get going, how often...
221 -0.173122   v222     Sleep was restless, how often ...
1   -0.163894   v2       Feeling of safety of walking a...
133 -0.144672   v134     Start of interview, year

### Visualizations
<a id="Visualizations"></a>

In [71]:
sns.pairplot(train_v3, hue="satisfied")